version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./code:/var/www/html
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - php
    links:
      - php
      - db

  php:
    image: php:7.4-fpm
    volumes:
      - ./code:/var/www/html
      - ./config/php:/usr/local/etc/php/conf.d/
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    links:
      - db
    depends_on:
      - db

  # Создание пользователя MySQL
  create-user:
    image: mysql:8.0
    command: >
      bash -c '
        echo "CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '\''${MYSQL_PASSWORD}'\'';" |
        mysql -h db -u root -p${MYSQL_ROOT_PASSWORD}
      '
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
